// tools/build_data.ts — generates the website's data files from the repo's
// own sources; the website is a consumer of the committed state, never a
// fork of it:
//   1. the rule tables are dumped from src/lib/rules.zig via `zig run` on a
//      temp copy (the tables are data-only and compile standalone), so alias
//      sets + policy fields can never drift from the CLI's;
//   2. fixtures/index-data.json — the committed index — is copied verbatim to
//      data/index.json (the site's rule index / #index section);
//   3. the from-identity channel (fixtures/from-identity, one 3-part
//      <h>-<p>-<m>.json per agent — the filename IS the agent id) is copied
//      VERBATIM to data/agents/<agent_id>.json — the site invents no envelope;
//      the from-capture channel's outputs never leave the repo: its STEMS are
//      scanned (never parsed) for the captured platforms, the only capture
//      fact on the wire;
//   4. data/agents.json projects the declarations (reciprocity of record,
//      state, email), the capture stems (platforms), and the index's free
//      axis into one row per agent.
// Every written file is validated through site/src/lib/schemas.ts before it
// lands — a zig dump change that breaks a shape fails this build, not a
// browser session.
// Outputs (site/public/data/, gitignored — regenerate before deploy):
//   registry.json           — the rule registry (harnesses/providers/models)
//   index.json              — the committed index file, verbatim
//   agents.json             — one row per agent
//   agents/<agent_id>.json  — the agent's from-identity fixture, verbatim

import { slugId, trailerEmail } from "../src/lib/registry.ts";
import {
  AgentsFileSchema,
  IdentityFileSchema,
  IndexDataFileSchema,
  RegistryFileSchema,
  type AgentRow,
  type Platform,
} from "../src/lib/schemas.ts";

const siteDir = new URL("../", import.meta.url);
const repoDir = new URL("../../", import.meta.url);

const ZIG_DUMP = `// generated by site/tools/build_data.ts — dumps the rule tables as JSON
const std = @import("std");
const rules = @import("rules.zig");

const Registry = struct {
    harnesses: []const rules.HarnessRule,
    providers: []const rules.ProviderRule,
    models: []const rules.ModelRule,
};

pub fn main(init: std.process.Init) u8 {
    const a = std.heap.page_allocator;
    const json = std.json.Stringify.valueAlloc(a, Registry{
        .harnesses = &rules.rulesForHarnesses,
        .providers = &rules.rulesForProviders,
        .models = &rules.rulesForModels,
    }, .{}) catch return 1;
    std.Io.Dir.cwd().writeFile(init.io, .{ .sub_path = "registry-rules.json", .data = json }) catch return 1;
    return 0;
}
`;

const PLATFORMS: Platform[] = ["darwin", "linux", "windows"];

function path(url: URL): string {
  return url.pathname;
}

async function dumpRules(): Promise<
  { harnesses: Record<string, unknown>[]; providers: Record<string, unknown>[]; models: Record<string, unknown>[] }
> {
  const tmp = await Deno.makeTempDir({ prefix: "agent-detect-site-" });
  try {
    await Deno.copyFile(path(repoDir) + "src/lib/rules.zig", tmp + "/rules.zig");
    await Deno.writeTextFile(tmp + "/dump.zig", ZIG_DUMP);
    const cmd = new Deno.Command("zig", {
      args: ["run", "dump.zig"],
      cwd: tmp,
      stdout: "piped",
      stderr: "piped",
    });
    const out = await cmd.output();
    if (!out.success) {
      throw new Error(`zig rules dump failed:\n${new TextDecoder().decode(out.stderr)}`);
    }
    return JSON.parse(await Deno.readTextFile(tmp + "/registry-rules.json"));
  } finally {
    await Deno.remove(tmp, { recursive: true });
  }
}

interface IdentityFile {
  /** the 3-part agent id — the filename IS the agent id */
  agentId: string;
  /** the file's raw bytes — copied verbatim, no envelope */
  bytes: Uint8Array;
  updatedAt: number;
  parsed: Record<string, unknown>;
}

const pRank = (arr: readonly Platform[]) => (v: Platform) => {
  const i = arr.indexOf(v);
  return i === -1 ? arr.length : i;
};

/** scan the from-identity channel — one 3-part <h>-<p>-<m>.json per agent. */
async function readIdentity(warnings: string[]): Promise<Map<string, IdentityFile>> {
  const dir = path(repoDir) + "fixtures/from-identity";
  const files = new Map<string, IdentityFile>();
  for await (const ent of Deno.readDir(dir)) {
    if (!ent.isFile || !ent.name.endsWith(".json")) continue;
    const stem = ent.name.slice(0, -".json".length);
    if (stem.split("-").length !== 3) {
      warnings.push(`skipping identity/${ent.name}: stem is not a 3-part <h>-<p>-<m> agent id`);
      continue;
    }
    const bytes = await Deno.readFile(`${dir}/${ent.name}`);
    let parsed: Record<string, unknown>;
    try {
      parsed = JSON.parse(new TextDecoder().decode(bytes));
    } catch (err) {
      warnings.push(`skipping identity/${ent.name}: ${err}`);
      continue;
    }
    if (!parsed.outputs) continue; // defensive: the writers never emit stubs
    const meta = (parsed.meta ?? {}) as Record<string, unknown>;
    files.set(stem, {
      agentId: stem,
      bytes,
      updatedAt: typeof meta.updated_at === "number" ? meta.updated_at : 0,
      parsed,
    });
  }
  return files;
}

/** scan the from-capture STEMS only — a capture file is written only on
 * success, so stem presence means a successful capture on that platform.
 * The outputs are never read: from-capture content never leaves the repo. */
async function readCapturePlatforms(warnings: string[]): Promise<Map<string, Platform[]>> {
  const dir = path(repoDir) + "fixtures/from-capture";
  const platforms = new Map<string, Platform[]>();
  for await (const ent of Deno.readDir(dir)) {
    if (!ent.isFile || !ent.name.endsWith(".json")) continue;
    const stem = ent.name.slice(0, -".json".length);
    const parts = stem.split("-");
    const plat = parts.pop();
    if (parts.length < 3 || !PLATFORMS.includes(plat as Platform)) {
      warnings.push(`skipping capture/${ent.name}: stem is not a 4-part <h>-<p>-<m>-<platform> id`);
      continue;
    }
    const agentId = parts.join("-");
    const list = platforms.get(agentId) ?? [];
    if (!list.includes(plat as Platform)) list.push(plat as Platform);
    platforms.set(agentId, list);
  }
  return platforms;
}

async function main() {
  const warnings: string[] = [];
  const generated_at = Math.floor(Date.now() / 1000);

  console.log("dumping the zig rule tables…");
  const dump = await dumpRules();
  const withId = (rules: Record<string, unknown>[]): Record<string, unknown>[] =>
    rules
      .map((r): Record<string, unknown> => ({ ...r, id: slugId(String(r.name)) }))
      .sort((x, y) => String(x.name).localeCompare(String(y.name)));
  const harnesses = withId(dump.harnesses);
  const providers = withId(dump.providers);
  const models = withId(dump.models);

  console.log("reading the from-identity channel…");
  const identity = await readIdentity(warnings);
  console.log("scanning the from-capture stems…");
  const captures = await readCapturePlatforms(warnings);

  const pRanker = pRank(PLATFORMS);
  const agentIds = [...identity.keys()].sort();

  console.log("reading the committed index…");
  const indexData = JSON.parse(await Deno.readTextFile(path(repoDir) + "fixtures/index-data.json"));

  await Deno.mkdir(path(siteDir) + "public/data/agents", { recursive: true });
  const rows: AgentRow[] = [];
  const emails = new Set<string>();
  for (const agentId of agentIds) {
    const file = identity.get(agentId)!;
    const outputs = file.parsed.outputs as Record<string, unknown>;
    const identify = outputs.identify as Record<string, unknown>;
    const email = trailerEmail(
      (outputs["trailer co-author"] as string) ?? (outputs["trailer assisted-by"] as string),
    ) ?? `${agentId}@local`;
    emails.add(email);
    const explain = outputs.explain as { state?: string } | null | undefined;
    const [h, p] = agentId.split("-");
    const m = agentId.slice(h.length + p.length + 2);
    rows.push({
      agent_id: agentId,
      harness: h,
      provider: p,
      model: m,
      email,
      reciprocal: identify.reciprocal === true,
      state: (explain?.state as AgentRow["state"]) ?? null,
      free: ((indexData.provider_map_to_free_models as Record<string, string[]>)[p] ?? []).includes(m),
      platforms: (captures.get(agentId) ?? []).sort((x, y) => pRanker(x) - pRanker(y)),
      updated_at: file.updatedAt,
    });
    // the agent's document is the from-identity fixture itself — verbatim bytes
    IdentityFileSchema.parse(file.parsed);
    await Deno.writeFile(path(siteDir) + `public/data/agents/${agentId}.json`, file.bytes);
  }

  const registry = { generated_at, harnesses, providers, models };
  const agentsFile = { generated_at, agents: rows };

  // pre-write validation — the schemas are the boundary
  RegistryFileSchema.parse(registry);
  AgentsFileSchema.parse(agentsFile);
  IndexDataFileSchema.parse(indexData);

  await Deno.writeTextFile(path(siteDir) + "public/data/index.json", JSON.stringify(indexData));
  await Deno.writeTextFile(path(siteDir) + "public/data/registry.json", JSON.stringify(registry));
  await Deno.writeTextFile(path(siteDir) + "public/data/agents.json", JSON.stringify(agentsFile));

  for (const w of warnings) console.warn("warn:", w);
  const domains = new Set([...emails].map((e) => e.split("@")[1] ?? ""));
  console.log(
    `registry: ${harnesses.length} harnesses, ${providers.length} providers, ${models.length} models\n` +
      `agents: ${rows.length} (reciprocal ${rows.filter((r) => r.reciprocal).length}, free ${rows.filter((r) => r.free).length}, ` +
      `with captures ${rows.filter((r) => r.platforms.length > 0).length})\n` +
      `emails: ${emails.size} distinct, domains: ${[...domains].join(", ")}\n` +
      `written to site/public/data/`,
  );
}

await main();
