// tools/build_data.ts — generates the website's data files from the repo's
// own sources; the website is a consumer of the committed state, never a
// fork of it:
//   1. the rule tables are dumped from src/lib/rules.zig via `zig run` on a
//      temp copy (the tables are data-only and compile standalone), so alias
//      sets + policy fields can never drift from the CLI's;
//   2. the fixture channels (fixtures/from-identity, fixtures/from-capture)
//      are grouped per combo and emitted verbatim.
// Outputs (site/public/data/, gitignored — regenerate before deploy):
//   registry.json           — the rule registry (harnesses/providers/models)
//   combos.json             — one compact row per h×p×m combo
//   agents/<agent_id>.json  — all fixtures of one combo (both channels, verbatim outputs)

import { slugId, trailerEmail } from "../src/lib/registry.ts";
import type { Channel, Platform } from "../src/lib/registry.ts";

const siteDir = new URL("../", import.meta.url);
const repoDir = new URL("../../", import.meta.url);

const ZIG_DUMP = `// generated by site/tools/build_data.ts — dumps the rule tables as JSON
const std = @import("std");
const rules = @import("rules.zig");

const Registry = struct {
    harnesses: []const rules.HarnessRule,
    providers: []const rules.ProviderRule,
    models: []const rules.ModelRule,
};

pub fn main(init: std.process.Init) u8 {
    const a = std.heap.page_allocator;
    const json = std.json.Stringify.valueAlloc(a, Registry{
        .harnesses = &rules.rulesForHarnesses,
        .providers = &rules.rulesForProviders,
        .models = &rules.rulesForModels,
    }, .{}) catch return 1;
    std.Io.Dir.cwd().writeFile(init.io, .{ .sub_path = "registry-rules.json", .data = json }) catch return 1;
    return 0;
}
`;

const PLATFORMS: Platform[] = ["darwin", "linux", "windows"];
const CHANNELS: Channel[] = ["capture", "identity"]; // richer channel first

function path(url: URL): string {
  return url.pathname;
}

async function dumpRules(): Promise<
  { harnesses: Record<string, unknown>[]; providers: Record<string, unknown>[]; models: Record<string, unknown>[] }
> {
  const tmp = await Deno.makeTempDir({ prefix: "agent-detect-site-" });
  try {
    await Deno.copyFile(path(repoDir) + "src/lib/rules.zig", tmp + "/rules.zig");
    await Deno.writeTextFile(tmp + "/dump.zig", ZIG_DUMP);
    const cmd = new Deno.Command("zig", {
      args: ["run", "dump.zig"],
      cwd: tmp,
      stdout: "piped",
      stderr: "piped",
    });
    const out = await cmd.output();
    if (!out.success) {
      throw new Error(`zig rules dump failed:\n${new TextDecoder().decode(out.stderr)}`);
    }
    return JSON.parse(await Deno.readTextFile(tmp + "/registry-rules.json"));
  } finally {
    await Deno.remove(tmp, { recursive: true });
  }
}

interface FixtureEntry {
  id: string;
  platform: Platform;
  channel: Channel;
  updated_at: number;
  meta: Record<string, unknown>;
  outputs: Record<string, unknown>;
}

interface Combo {
  agent_id: string;
  harness: string;
  provider: string;
  model: string;
  email: string;
  reciprocal: boolean;
  state: string | null;
  platforms: Platform[];
  channels: Channel[];
  updated_at: number;
  fixtures: { id: string; platform: Platform; channel: Channel }[];
}

const rank = (arr: readonly string[]) => (v: string) => {
  const i = arr.indexOf(v);
  return i === -1 ? arr.length : i;
};

async function readChannel(channel: Channel, warnings: string[]): Promise<Map<string, FixtureEntry[]>> {
  const dir = path(repoDir) + `fixtures/from-${channel}`;
  const groups = new Map<string, FixtureEntry[]>();
  for await (const ent of Deno.readDir(dir)) {
    if (!ent.isFile || !ent.name.endsWith(".json")) continue;
    const stem = ent.name.slice(0, -".json".length);
    const parts = stem.split("-");
    if (parts.length !== 4 || !PLATFORMS.includes(parts[3] as Platform)) {
      warnings.push(`skipping ${channel}/${ent.name}: stem does not split 4-way`);
      continue;
    }
    const [h, p, m, platform] = parts;
    const agent_id = `${h}-${p}-${m}`;
    let file: { meta?: Record<string, unknown>; outputs?: Record<string, unknown> };
    try {
      file = JSON.parse(await Deno.readTextFile(`${dir}/${ent.name}`));
    } catch (err) {
      warnings.push(`skipping ${channel}/${ent.name}: ${err}`);
      continue;
    }
    if (!file.outputs) continue; // defensive: the writers never emit stubs
    const entry: FixtureEntry = {
      id: stem,
      platform: platform as Platform,
      channel,
      updated_at: typeof file.meta?.updated_at === "number" ? file.meta.updated_at : 0,
      meta: file.meta ?? {},
      outputs: file.outputs,
    };
    const list = groups.get(agent_id) ?? [];
    list.push(entry);
    groups.set(agent_id, list);
  }
  return groups;
}

async function main() {
  const warnings: string[] = [];
  const generated_at = Math.floor(Date.now() / 1000);

  console.log("dumping the zig rule tables…");
  const dump = await dumpRules();
  const withId = (rules: Record<string, unknown>[]): Record<string, unknown>[] =>
    rules
      .map((r): Record<string, unknown> => ({ ...r, id: slugId(String(r.name)) }))
      .sort((x, y) => String(x.name).localeCompare(String(y.name)));
  const harnesses = withId(dump.harnesses);
  const providers = withId(dump.providers);
  const models = withId(dump.models);

  console.log("reading fixture channels…");
  const identity = await readChannel("identity", warnings);
  const capture = await readChannel("capture", warnings);
  const agentIds = [...new Set([...identity.keys(), ...capture.keys()])].sort();

  const pRank = rank(PLATFORMS);
  const cRank = rank(CHANNELS);
  const combos: Combo[] = [];
  const emails = new Set<string>();

  await Deno.mkdir(path(siteDir) + "public/data/agents", { recursive: true });
  for (const agent_id of agentIds) {
    const fixtures = [
      ...(identity.get(agent_id) ?? []),
      ...(capture.get(agent_id) ?? []),
    ].sort((x, y) =>
      (pRank(x.platform) - pRank(y.platform)) || (cRank(x.channel) - cRank(y.channel)) || (y.updated_at - x.updated_at)
    );
    const latest = fixtures[0];
    const identify = latest.outputs.identify as Record<string, unknown> | undefined;
    const email = fixtures
      .map((f) => trailerEmail((f.outputs["trailer co-author"] as string) ?? (f.outputs["trailer assisted-by"] as string)))
      .find((e): e is string => !!e) ?? `${agent_id}@local`;
    emails.add(email);
    const explains = fixtures.map((f) => f.outputs.explain as { state?: string } | null | undefined).find((e) => e?.state);
    const parts = agent_id.split("-");
    combos.push({
      agent_id,
      harness: parts[0],
      provider: parts[1],
      model: parts.slice(2).join("-"),
      email,
      reciprocal: identify?.reciprocal === true,
      state: (explains?.state as string) ?? null,
      platforms: [...new Set(fixtures.map((f) => f.platform))].sort((x, y) => pRank(x) - pRank(y)),
      channels: [...new Set(fixtures.map((f) => f.channel))].sort((x, y) => cRank(x) - cRank(y)),
      updated_at: Math.max(...fixtures.map((f) => f.updated_at)),
      fixtures: fixtures.map((f) => ({ id: f.id, platform: f.platform, channel: f.channel })),
    });

    const agentFile = {
      agent_id,
      harness: parts[0],
      provider: parts[1],
      model: parts.slice(2).join("-"),
      fixtures: fixtures.map((f) => ({
        id: f.id,
        platform: f.platform,
        channel: f.channel,
        updated_at: f.updated_at,
        meta: f.meta,
        outputs: f.outputs,
      })),
    };
    await Deno.writeTextFile(path(siteDir) + `public/data/agents/${agent_id}.json`, JSON.stringify(agentFile));
  }

  const registry = {
    generated_at,
    counts: { harnesses: harnesses.length, providers: providers.length, models: models.length },
    harnesses,
    providers,
    models,
  };
  const combosFile = { generated_at, counts: { combos: combos.length, fixtures: agentIds.reduce((n, id) => n + (identity.get(id)?.length ?? 0) + (capture.get(id)?.length ?? 0), 0) }, combos };

  await Deno.writeTextFile(path(siteDir) + "public/data/registry.json", JSON.stringify(registry));
  await Deno.writeTextFile(path(siteDir) + "public/data/combos.json", JSON.stringify(combosFile));

  for (const w of warnings) console.warn("warn:", w);
  const domains = new Set([...emails].map((e) => e.split("@")[1] ?? ""));
  console.log(
    `registry: ${harnesses.length} harnesses, ${providers.length} providers, ${models.length} models\n` +
      `combos: ${combos.length} (reciprocal ${combos.filter((c) => c.reciprocal).length})\n` +
      `emails: ${emails.size} distinct, domains: ${[...domains].join(", ")}\n` +
      `written to site/public/data/`,
  );
}

await main();
